import { colors } from '@/lib/constants/colors';

export const mockEvents = [
  {
    id: '1',
    name: '大学入学',
    type: 'celebration',
    date: '2020-04-01',
    event_date: '2020-04-01',
    description: '念願の大学に合格し、新しい生活がスタート',
    location: '東京大学',
    color: colors.eventTypes.celebration,
    year: '2020',
    event_for: '自分',
  },
  {
    id: '2',
    name: '祖父の葬儀',
    type: 'funeral',
    date: '2021-08-20',
    event_date: '2021-08-20',
    description: '長い間お世話になった祖父との別れ',
    location: '故郷の寺',
    color: colors.eventTypes.funeral,
    year: '2021',
    event_for: '祖父',
  },
  {
    id: '3',
    name: '就職活動開始',
    type: 'other',
    date: '2022-03-01',
    event_date: '2022-03-01',
    description: '将来のキャリアを考え、就職活動を本格的に開始',
    location: 'オンライン',
    color: colors.eventTypes.other,
    year: '2022',
    event_for: '自分',
  },
  {
    id: '4',
    name: '内定獲得',
    type: 'celebration',
    date: '2023-06-15',
    event_date: '2023-06-15',
    description: '第一志望の企業から内定をいただく',
    location: '東京',
    color: colors.eventTypes.celebration,
    year: '2023',
    event_for: '自分',
  },
  {
    id: '5',
    name: '卒業式',
    type: 'celebration',
    date: '2024-03-25',
    event_date: '2024-03-25',
    description: '4年間の大学生活を終え、社会人へ',
    location: '東京大学',
    color: colors.eventTypes.celebration,
    year: '2024',
    event_for: '自分',
  },
  {
    id: '6',
    name: '入社式',
    type: 'other',
    date: '2024-04-01',
    event_date: '2024-04-01',
    description: '社会人としての第一歩',
    location: '本社',
    color: colors.eventTypes.other,
    year: '2024',
    event_for: '自分',
  },
  {
    id: '7',
    name: '友人の結婚式',
    type: 'wedding',
    date: '2024-09-20',
    event_date: '2024-09-20',
    description: '大学時代の親友の幸せな門出',
    location: '横浜',
    color: colors.eventTypes.wedding,
    year: '2024',
    event_for: '友人',
  },
  {
    id: '8',
    name: '自分の結婚式',
    type: 'wedding',
    date: '2025-06-15',
    event_date: '2025-06-15',
    description: '家族と親しい友人だけの小さな式',
    location: '東京',
    color: colors.eventTypes.wedding,
    year: '2025',
    event_for: '自分',
  },
  {
    id: '9',
    name: '新居購入',
    type: 'celebration',
    date: '2025-10-01',
    event_date: '2025-10-01',
    description: '夢のマイホームを購入',
    location: '横浜市',
    color: colors.eventTypes.celebration,
    year: '2025',
    event_for: '家族',
  },
  {
    id: '10',
    name: '長女の誕生',
    type: 'celebration',
    date: '2026-03-15',
    event_date: '2026-03-15',
    description: '元気な女の子が誕生しました',
    location: '市立病院',
    color: colors.eventTypes.celebration,
    year: '2026',
    event_for: '子供',
  },
  {
    id: '11',
    name: '長女の1歳の誕生日',
    type: 'celebration',
    date: '2027-03-15',
    event_date: '2027-03-15',
    description: '初めての誕生日パーティー',
    location: '自宅',
    color: colors.eventTypes.celebration,
    year: '2027',
    event_for: '子供',
  },
  {
    id: '12',
    name: '次女の誕生',
    type: 'celebration',
    date: '2028-07-10',
    event_date: '2028-07-10',
    description: '二人目の女の子が誕生',
    location: '市立病院',
    color: colors.eventTypes.celebration,
    year: '2028',
    event_for: '子供',
  },
  {
    id: '13',
    name: '長女の七五三',
    type: 'celebration',
    date: '2029-11-15',
    event_date: '2029-11-15',
    description: '3歳の七五三、着物姿がとても可愛い',
    location: '地元の神社',
    color: colors.eventTypes.celebration,
    year: '2029',
    event_for: '子供',
  },
  {
    id: '14',
    name: '長女の幼稚園入園',
    type: 'celebration',
    date: '2029-04-08',
    event_date: '2029-04-08',
    description: '初めての集団生活がスタート',
    location: '市立幼稚園',
    color: colors.eventTypes.celebration,
    year: '2029',
    event_for: '子供',
  },
  {
    id: '15',
    name: '長女の運動会',
    type: 'celebration',
    date: '2029-10-12',
    event_date: '2029-10-12',
    description: '初めての運動会、かけっこ頑張った',
    location: '幼稚園グラウンド',
    color: colors.eventTypes.celebration,
    year: '2029',
    event_for: '子供',
  },
  {
    id: '16',
    name: '次女の七五三',
    type: 'celebration',
    date: '2031-11-15',
    event_date: '2031-11-15',
    description: '3歳の七五三、姉妹で記念撮影',
    location: '地元の神社',
    color: colors.eventTypes.celebration,
    year: '2031',
    event_for: '子供',
  },
  {
    id: '17',
    name: '長女の小学校入学',
    type: 'celebration',
    date: '2032-04-06',
    event_date: '2032-04-06',
    description: 'ピカピカのランドセルで小学生に',
    location: '市立小学校',
    color: colors.eventTypes.celebration,
    year: '2032',
    event_for: '子供',
  },
  {
    id: '18',
    name: '長女の誕生日パーティー',
    type: 'celebration',
    date: '2033-03-15',
    event_date: '2033-03-15',
    description: '7歳の誕生日、友達を招いてパーティー',
    location: '自宅',
    color: colors.eventTypes.celebration,
    year: '2033',
    event_for: '子供',
  },
  {
    id: '19',
    name: '次女の幼稚園入園',
    type: 'celebration',
    date: '2031-04-08',
    event_date: '2031-04-08',
    description: '姉と同じ幼稚園に入園',
    location: '市立幼稚園',
    color: colors.eventTypes.celebration,
    year: '2031',
    event_for: '子供',
  },
  {
    id: '20',
    name: '家族旅行（沖縄）',
    type: 'celebration',
    date: '2033-08-10',
    event_date: '2033-08-10',
    description: '家族4人で初めての沖縄旅行',
    location: '沖縄県',
    color: colors.eventTypes.celebration,
    year: '2033',
    event_for: '家族',
  },
];

export const mockTasks = {
  '8': [
    {
      id: 't1',
      title: '式場の予約',
      description: '候補の式場を3つピックアップして見学',
      phase: '準備（6ヶ月前）',
      due_date: '2024-12-15',
      is_completed: true,
      assigned_to: '山田太郎',
    },
    {
      id: 't2',
      title: '招待状のデザイン決定',
      description: 'デザイナーと打ち合わせ',
      phase: '準備（3ヶ月前）',
      due_date: '2025-03-15',
      is_completed: true,
      assigned_to: '佐藤花子',
    },
    {
      id: 't3',
      title: '招待状の発送',
      description: 'ゲスト全員に招待状を送付',
      phase: '準備（3ヶ月前）',
      due_date: '2025-04-01',
      is_completed: false,
      assigned_to: '田中美咲',
    },
    {
      id: 't4',
      title: 'ドレスの最終フィッティング',
      description: 'ウェディングドレスの最終調整',
      phase: '直前（1ヶ月前）',
      due_date: '2025-05-15',
      is_completed: false,
      assigned_to: '自分',
    },
    {
      id: 't5',
      title: '席次表の確定',
      description: '出欠状況を確認して席次を決定',
      phase: '直前（1ヶ月前）',
      due_date: '2025-05-20',
      is_completed: false,
      assigned_to: '山田太郎',
    },
  ],
  '13': [
    {
      id: 't6',
      title: '着物のレンタル予約',
      description: '七五三用の着物をレンタル',
      phase: '準備（2ヶ月前）',
      due_date: '2029-09-15',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't7',
      title: '写真スタジオの予約',
      description: '記念写真の撮影予約',
      phase: '準備（1ヶ月前）',
      due_date: '2029-10-15',
      is_completed: true,
      assigned_to: 'お父さん',
    },
    {
      id: 't8',
      title: '神社でのご祈祷予約',
      description: '七五三のご祈祷予約',
      phase: '準備（2週間前）',
      due_date: '2029-11-01',
      is_completed: false,
      assigned_to: 'お母さん',
    },
    {
      id: 't9',
      title: '食事会の予約',
      description: '家族で食事会',
      phase: '当日',
      due_date: '2029-11-15',
      is_completed: false,
      assigned_to: 'お父さん',
    },
  ],
  '18': [
    {
      id: 't10',
      title: '誕生日ケーキの予約',
      description: '子供の好きなケーキを予約',
      phase: '準備（1週間前）',
      due_date: '2033-03-08',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't11',
      title: 'プレゼントの購入',
      description: '娘が欲しがっていたおもちゃ',
      phase: '準備（1週間前）',
      due_date: '2033-03-08',
      is_completed: true,
      assigned_to: 'お父さん',
    },
    {
      id: 't12',
      title: '友達への招待連絡',
      description: '仲良しのお友達5人を招待',
      phase: '準備（2週間前）',
      due_date: '2033-03-01',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't13',
      title: '部屋の飾り付け',
      description: 'バルーンと飾り付けの準備',
      phase: '当日',
      due_date: '2033-03-15',
      is_completed: false,
      assigned_to: '両親',
    },
  ],
  '7': [
    {
      id: 't14',
      title: 'ご祝儀の準備',
      description: '新札を用意してご祝儀袋に入れる',
      phase: '準備（1週間前）',
      due_date: '2024-09-13',
      is_completed: true,
      assigned_to: '自分',
    },
    {
      id: 't15',
      title: 'スーツのクリーニング',
      description: '結婚式用のスーツをクリーニング',
      phase: '準備（1週間前）',
      due_date: '2024-09-10',
      is_completed: true,
      assigned_to: '自分',
    },
    {
      id: 't16',
      title: 'お祝いメッセージの準備',
      description: '受付で渡すメッセージカードを準備',
      phase: '準備（3日前）',
      due_date: '2024-09-17',
      is_completed: false,
      assigned_to: '自分',
    },
  ],
  '10': [
    {
      id: 't17',
      title: '出産準備品の購入',
      description: 'ベビーベッド、おむつ、肌着など',
      phase: '準備（1ヶ月前）',
      due_date: '2026-02-15',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't18',
      title: '病院の入院予約',
      description: '出産予定日の入院予約',
      phase: '準備（2ヶ月前）',
      due_date: '2026-01-15',
      is_completed: true,
      assigned_to: 'お父さん',
    },
    {
      id: 't19',
      title: '名前の決定',
      description: '赤ちゃんの名前を考える',
      phase: '準備（1ヶ月前）',
      due_date: '2026-02-15',
      is_completed: true,
      assigned_to: '両親',
    },
    {
      id: 't20',
      title: '出生届の提出',
      description: '役所に出生届を提出',
      phase: '出産後（14日以内）',
      due_date: '2026-03-29',
      is_completed: false,
      assigned_to: 'お父さん',
    },
  ],
  '14': [
    {
      id: 't21',
      title: '入園願書の提出',
      description: '幼稚園の願書を提出',
      phase: '準備（6ヶ月前）',
      due_date: '2028-10-08',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't22',
      title: '入園用品の購入',
      description: 'バッグ、上履き、お弁当箱など',
      phase: '準備（1ヶ月前）',
      due_date: '2029-03-08',
      is_completed: true,
      assigned_to: 'お母さん',
    },
    {
      id: 't23',
      title: '名前の記入',
      description: 'すべての持ち物に名前を記入',
      phase: '準備（1週間前）',
      due_date: '2029-04-01',
      is_completed: false,
      assigned_to: 'お母さん',
    },
  ],
};

export const mockGuests = {
  '8': [
    {
      id: 'g1',
      name: '山田太郎',
      relationship: '友人',
      phone: '090-1234-5678',
      email: 'taro@example.com',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
    {
      id: 'g2',
      name: '佐藤花子',
      relationship: '友人',
      phone: '090-2345-6789',
      email: 'hanako@example.com',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
    {
      id: 'g3',
      name: '鈴木一郎',
      relationship: '同僚',
      phone: '090-3456-7890',
      email: 'ichiro@example.com',
      attendance_status: 'pending',
      gift_amount: 0,
    },
    {
      id: 'g4',
      name: '田中美咲',
      relationship: '親族',
      phone: '090-4567-8901',
      email: 'misaki@example.com',
      attendance_status: 'attending',
      gift_amount: 50000,
    },
    {
      id: 'g5',
      name: '高橋健太',
      relationship: '友人',
      phone: '090-5678-9012',
      email: 'kenta@example.com',
      attendance_status: 'declined',
      gift_amount: 0,
    },
  ],
  '13': [
    {
      id: 'g6',
      name: '祖父母（父方）',
      relationship: '親族',
      phone: '090-1111-2222',
      email: '',
      attendance_status: 'attending',
      gift_amount: 50000,
    },
    {
      id: 'g7',
      name: '祖父母（母方）',
      relationship: '親族',
      phone: '090-3333-4444',
      email: '',
      attendance_status: 'attending',
      gift_amount: 50000,
    },
    {
      id: 'g8',
      name: '叔父夫婦',
      relationship: '親族',
      phone: '090-5555-6666',
      email: '',
      attendance_status: 'attending',
      gift_amount: 10000,
    },
    {
      id: 'g9',
      name: '叔母夫婦',
      relationship: '親族',
      phone: '090-7777-8888',
      email: '',
      attendance_status: 'attending',
      gift_amount: 10000,
    },
  ],
  '18': [
    {
      id: 'g10',
      name: 'さくらちゃん',
      relationship: '友達',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 0,
    },
    {
      id: 'g11',
      name: 'あやちゃん',
      relationship: '友達',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 0,
    },
    {
      id: 'g12',
      name: 'ゆいちゃん',
      relationship: '友達',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 0,
    },
    {
      id: 'g13',
      name: 'はるくん',
      relationship: '友達',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 0,
    },
    {
      id: 'g14',
      name: 'たくくん',
      relationship: '友達',
      phone: '',
      email: '',
      attendance_status: 'pending',
      gift_amount: 0,
    },
  ],
  '7': [
    {
      id: 'g15',
      name: '自分',
      relationship: '友人',
      phone: '090-1234-5678',
      email: '',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
  ],
  '10': [
    {
      id: 'g16',
      name: '祖父母（父方）',
      relationship: '親族',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 100000,
    },
    {
      id: 'g17',
      name: '祖父母（母方）',
      relationship: '親族',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 100000,
    },
    {
      id: 'g18',
      name: '叔父叔母',
      relationship: '親族',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
  ],
  '14': [
    {
      id: 'g19',
      name: '祖父母（父方）',
      relationship: '親族',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
    {
      id: 'g20',
      name: '祖父母（母方）',
      relationship: '親族',
      phone: '',
      email: '',
      attendance_status: 'attending',
      gift_amount: 30000,
    },
  ],
};

export const mockExpenses = {
  '8': [
    {
      id: 'e1',
      type: 'expense',
      amount: 1500000,
      category: '式場費用',
      description: '式場使用料・料理・飲み物',
      date: '2024-12-01',
    },
    {
      id: 'e2',
      type: 'expense',
      amount: 300000,
      category: '衣装',
      description: 'ウェディングドレス・タキシードレンタル',
      date: '2025-01-15',
    },
    {
      id: 'e3',
      type: 'expense',
      amount: 150000,
      category: '写真・動画',
      description: 'カメラマン・ビデオグラファー',
      date: '2025-02-01',
    },
    {
      id: 'e4',
      type: 'expense',
      amount: 80000,
      category: '装花',
      description: 'ブーケ・会場装花',
      date: '2025-03-01',
    },
    {
      id: 'e5',
      type: 'expense',
      amount: 50000,
      category: '招待状・席札',
      description: '印刷・デザイン費用',
      date: '2025-03-10',
    },
  ],
  '13': [
    {
      id: 'e6',
      type: 'expense',
      amount: 50000,
      category: '着物レンタル',
      description: '七五三用の着物レンタル',
      date: '2029-09-15',
    },
    {
      id: 'e7',
      type: 'expense',
      amount: 80000,
      category: '写真撮影',
      description: 'スタジオ撮影・アルバム代',
      date: '2029-10-15',
    },
    {
      id: 'e8',
      type: 'expense',
      amount: 10000,
      category: 'ご祈祷',
      description: '神社でのご祈祷料',
      date: '2029-11-15',
    },
    {
      id: 'e9',
      type: 'expense',
      amount: 30000,
      category: '食事会',
      description: '家族での食事会',
      date: '2029-11-15',
    },
    {
      id: 'e10',
      type: 'income',
      amount: 120000,
      category: 'お祝い金',
      description: '祖父母・親族からのお祝い',
      date: '2029-11-15',
    },
  ],
  '18': [
    {
      id: 'e11',
      type: 'expense',
      amount: 8000,
      category: 'ケーキ',
      description: '誕生日ケーキ',
      date: '2033-03-15',
    },
    {
      id: 'e12',
      type: 'expense',
      amount: 15000,
      category: 'プレゼント',
      description: '誕生日プレゼント',
      date: '2033-03-10',
    },
    {
      id: 'e13',
      type: 'expense',
      amount: 5000,
      category: '飾り付け',
      description: 'バルーン・飾り付け',
      date: '2033-03-12',
    },
    {
      id: 'e14',
      type: 'expense',
      amount: 12000,
      category: '食事',
      description: 'パーティー用の食材・飲み物',
      date: '2033-03-15',
    },
  ],
  '7': [
    {
      id: 'e15',
      type: 'expense',
      amount: 30000,
      category: 'ご祝儀',
      description: '友人の結婚式のご祝儀',
      date: '2024-09-20',
    },
    {
      id: 'e16',
      type: 'expense',
      amount: 5000,
      category: '交通費',
      description: '式場までの交通費',
      date: '2024-09-20',
    },
    {
      id: 'e17',
      type: 'expense',
      amount: 3000,
      category: 'その他',
      description: 'クリーニング代',
      date: '2024-09-10',
    },
  ],
  '10': [
    {
      id: 'e18',
      type: 'expense',
      amount: 150000,
      category: '出産費用',
      description: '病院の出産費用',
      date: '2026-03-15',
    },
    {
      id: 'e19',
      type: 'expense',
      amount: 80000,
      category: 'ベビー用品',
      description: 'ベビーベッド、チャイルドシートなど',
      date: '2026-02-15',
    },
    {
      id: 'e20',
      type: 'expense',
      amount: 30000,
      category: '肌着・衣類',
      description: '新生児用の肌着と衣類',
      date: '2026-02-20',
    },
    {
      id: 'e21',
      type: 'income',
      amount: 420000,
      category: '出産一時金',
      description: '健康保険からの出産一時金',
      date: '2026-04-01',
    },
    {
      id: 'e22',
      type: 'income',
      amount: 230000,
      category: 'お祝い金',
      description: '祖父母・親族からのお祝い',
      date: '2026-03-20',
    },
  ],
  '14': [
    {
      id: 'e23',
      type: 'expense',
      amount: 50000,
      category: '入園準備金',
      description: '幼稚園の入園準備金',
      date: '2029-03-01',
    },
    {
      id: 'e24',
      type: 'expense',
      amount: 35000,
      category: '用品購入',
      description: 'バッグ、上履き、お弁当箱など',
      date: '2029-03-08',
    },
    {
      id: 'e25',
      type: 'expense',
      amount: 15000,
      category: '制服',
      description: '幼稚園の制服',
      date: '2029-03-05',
    },
    {
      id: 'e26',
      type: 'income',
      amount: 60000,
      category: 'お祝い金',
      description: '祖父母からの入園祝い',
      date: '2029-04-08',
    },
  ],
};
